USE [GD1C2020]
GO

DECLARE @vEsquema VARCHAR(30)
SET @vEsquema = 'LOS_SEQUEL_BLINDERS'

if not exists (select * from sys.schemas where name = @vEsquema)
begin
	exec ('CREATE SCHEMA '+@vEsquema)
	print 'Esquema creado!'
end
else
begin
	-- BORRO TODO LO QUE HAYA EN EL ESQUEMA
	DECLARE @Sql VARCHAR(MAX)
		  , @Schema varchar(20)

	SET @Schema = 'LOS_SEQUEL_BLINDERS'

	--tables
	SELECT @Sql = COALESCE(@Sql,'') + 'DROP TABLE %SCHEMA%.' + TABLE_NAME + ';' + CHAR(13)
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = @Schema
		AND TABLE_TYPE = 'BASE TABLE'
	ORDER BY TABLE_NAME

	--views
	SELECT @Sql = COALESCE(@Sql,'') + 'DROP VIEW %SCHEMA%.' + QUOTENAME(TABLE_NAME) + ';' + CHAR(13)
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = @Schema
		AND TABLE_TYPE = 'VIEW'
	ORDER BY TABLE_NAME

	--Procedures
	SELECT @Sql = COALESCE(@Sql,'') + 'DROP PROCEDURE %SCHEMA%.' + QUOTENAME(ROUTINE_NAME) + ';' + CHAR(13)
	FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_SCHEMA = @Schema
		AND ROUTINE_TYPE = 'PROCEDURE'
	ORDER BY ROUTINE_NAME

	--Functions
	SELECT @Sql = COALESCE(@Sql,'') + 'DROP FUNCTION %SCHEMA%.' + QUOTENAME(ROUTINE_NAME) + ';' + CHAR(13)
	FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_SCHEMA = @Schema
		AND ROUTINE_TYPE = 'FUNCTION'
	ORDER BY ROUTINE_NAME

	SELECT @Sql = COALESCE(REPLACE(@Sql,'%SCHEMA%',@Schema), '')
	exec sp_sqlexec @Sql
end
go
-- CREO TABLAS
CREATE TABLE LOS_SEQUEL_BLINDERS.EMPRESA(
	EMPRESA_ID int PRIMARY KEY IDENTITY,
	EMPRESA_RAZON_SOCIAL NVARCHAR(255) NOT NULL
)
CREATE TABLE LOS_SEQUEL_BLINDERS.COMPRA(
	COMPRA_NRO decimal(18, 0) PRIMARY KEY,
	EMPRESA_ID int FOREIGN KEY REFERENCES LOS_SEQUEL_BLINDERS.EMPRESA(EMPRESA_ID),
	COMPRA_FECHA datetime2(3) NOT NULL
)-- CARGO REGISTROS-- EMPRESASINSERT INTO LOS_SEQUEL_BLINDERS.EMPRESA SELECT DISTINCT	EMPRESA_RAZON_SOCIALFROM gd_esquema.MaestraWHERE EMPRESA_RAZON_SOCIAL is not null;-- COMPRASINSERT INTO LOS_SEQUEL_BLINDERS.COMPRASELECT DISTINCT	COMPRA_NUMERO,	E.EMPRESA_ID,	COMPRA_FECHAFROM gd_esquema.Maestra M LEFT JOIN LOS_SEQUEL_BLINDERS.EMPRESA E on	 M.EMPRESA_RAZON_SOCIAL = E.EMPRESA_RAZON_SOCIALWHERE COMPRA_NUMERO is not null;